import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient();

const transformSeedData = (rawData) => {
    const eventData = rawData.eventData[0];

    return {
        // Event data
        eventTitle: eventData.eventTitle,
        description: eventData.description,
        location: eventData.location,
        eventType: eventData.eventType,
        capacity: parseInt(eventData.capacity),
        price: parseInt(eventData.price),
        // Convert string dates to Date objects
        eventDate: new Date(eventData.eventDate),
        eventDeadline: new Date(eventData.eventDeadline),
        eventImage: eventData.eventImage || null,

        // Nested create for formFields
        formFields: {
            create: rawData.fields.map((field) => ({
                fieldName: field.fieldName,
                label: field.label,
                fieldType: field.fieldType,
                isRequired: field.isRequired,
                options: field.options || null,
                // fieldId is likely not needed if it's auto-generated by Prisma
            }))
        }
    };
};

// --- Raw Data Sets ---
// Use data in the same format you receive from your frontend
const rawSeedData = [
    // 💾 Set 1 (From your example)
    {
        eventData: [{
            eventTitle: "Sindbad's Adventure",
            description: "A great storytelling workshop for all ages.",
            location: "Aliabazar Community Hall",
            eventType: "workshop",
            capacity: "300",
            price: "498",
            eventDate: "2025-11-10T18:00:00.000Z",
            eventDeadline: "2025-11-08T18:00:00.000Z",
            eventImage: ""
        }],
        fields: [{
            fieldName: "Name",
            label: "Your Full Name",
            fieldType: "text",
            isRequired: true,
            options: "",
            fieldId: "999de1f9"
        }]
    },
    // 💾 Set 2: A different event type with multiple fields
    {
        eventData: [{
            eventTitle: "Tech Innovators Summit",
            description: "An annual competition for new tech startups.",
            location: "City Convention Center",
            eventType: "competition",
            capacity: "1500",
            price: "1500",
            eventDate: "2025-12-05T10:00:00.000Z",
            eventDeadline: "2025-11-30T23:59:59.000Z",
            eventImage: "summit_image_url"
        }],
        fields: [
            { fieldName: "Email", label: "Contact Email", fieldType: "email", isRequired: true, options: "" },
            { fieldName: "TeamSize", label: "Team Size", fieldType: "number", isRequired: true, options: "" }
        ]
    },
    // 💾 Set 3: A free event
    {
        eventData: [{
            eventTitle: "Local Park Cleanup",
            description: "Volunteer day to help clean up the riverbank park.",
            location: "Riverfront Park",
            eventType: "social",
            capacity: "50",
            price: "0",
            eventDate: "2025-10-20T08:00:00.000Z",
            eventDeadline: "2025-10-18T18:00:00.000Z",
            eventImage: ""
        }],
        fields: [
            { fieldName: "ShirtSize", label: "T-Shirt Size", fieldType: "select", isRequired: false, options: "S, M, L, XL" }
        ]
    },
    // 💾 Set 4: A smaller, music-focused event
    {
        eventData: [{
            eventTitle: "Acoustic Open Mic Night",
            description: "Local artists perform in a cozy setting.",
            location: "The Old Coffee House",
            eventType: "performance",
            capacity: "80",
            price: "250",
            eventDate: "2025-11-15T20:00:00.000Z",
            eventDeadline: "2025-11-14T19:00:00.000Z",
            eventImage: ""
        }],
        fields: [
            { fieldName: "ShirtSize", label: "T-Shirt Size", fieldType: "select", isRequired: false, options: "S, M, L, XL" }
        ] // No extra fields needed for this event
    }
];

const seed = async () => {
    for (const rawData of rawSeedData) {
        try {
            // 1. Transform the raw data
            const dataToCreate = transformSeedData(rawData);

            // 2. Use prisma.event.create for nested writes
            const event = await prisma.event.create({
                data: dataToCreate,
                include: {
                    formFields: true
                }
            });
            console.log(`✅ Created event: ${event.eventTitle} (ID: ${event.id})`);
        } catch (error) {
            console.error(`❌ Error seeding event: ${rawData.eventData[0].eventTitle}`, error);
        }
    }

    console.log(`Database seed finished! Created ${rawSeedData.length} events.`);
}

seed()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });